# Generated by Django 4.2 on 2023-04-18 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_photo_title_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='photos',
        ),
        migrations.AddField(
            model_name='photo',
            name='tags',
            field=models.ManyToManyField(related_name='photos', to='api.tag'),
        ),
    ]
