# Generated by Django 4.2 on 2023-04-18 11:08

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_tag_photos_photo_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(db_index=True, max_length=20, unique=True, validators=[api.models.tag_name_validator]),
        ),
    ]
